# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('players', models.IntegerField(default=4)),
                ('practice_iteration', models.IntegerField(default=5)),
                ('main_iteration', models.IntegerField(default=10)),
                ('feedback_show', models.IntegerField(default=5)),
                ('feedback_type', models.CharField(choices=[('N', '안내 - Notice'), ('W', '경고 - Warning')], max_length=1)),
                ('feedback_contents', models.CharField(max_length=50)),
                ('token_type', models.CharField(choices=[('t', '토큰'), ('c', '사이버머니'), ('p', '점수')], max_length=1)),
                ('token_given', models.IntegerField(default=200)),
                ('point_calc', models.IntegerField(default=2)),
                ('reward', models.CharField(max_length=50)),
                ('punish_bool', models.BooleanField(default=False)),
                ('conditional_type', models.CharField(choices=[('u', 'unconditional'), ('c', 'conditional')], max_length=1)),
                ('wait_time', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donate', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
    ]
