# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170201_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='range_down',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='game',
            name='range_up',
            field=models.IntegerField(default=7000),
        ),
        migrations.AlterField(
            model_name='game',
            name='feedback_show',
            field=models.IntegerField(default=5, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_iteration',
            field=models.IntegerField(default=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='practice_iteration',
            field=models.IntegerField(default=5, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_donate',
            field=models.CharField(default='', max_length=300),
        ),
    ]
