# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170202_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='feedback_show',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_iteration',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='practice_iteration',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
