# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170222_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='token_type',
            field=models.CharField(choices=[(b't', b'\xed\x86\xa0\xed\x81\xb0'), (b'c', b'\xec\x82\xac\xec\x9d\xb4\xeb\xb2\x84\xeb\xa8\xb8\xeb\x8b\x88'), (b'p', b'\xec\xa0\x90\xec\x88\x98')], max_length=1),
        ),
    ]
