# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170526_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='token_type',
            field=models.CharField(choices=[('t', '토큰'), ('c', '사이버머니'), ('p', '점수')], max_length=1),
        ),
    ]
